services:
  mysql:
    image: mysql:8.0
    container_name: mysql_nutricion
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nutricion_db
      MYSQL_USER: nutricion_user
      MYSQL_PASSWORD: nutricion_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    container_name: frontend_nutricion
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    container_name: backend_nutricion
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: nutricion_user
      DB_PASSWORD: nutricion_pass
      DB_NAME: nutricion_db
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: ["node", "app.js"]
    env_file:
      - .env

volumes:
  mysql_data: